server:
  port: 8888

spring:
  security:
    user:
      name: config
      password: password

eureka:
  instance:
    metadata-map:
      # DiscoveryClientConfigServiceBootstrapConfiguration#refresh
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}

---

spring.profiles: dev
eureka.client.service-url.defaultZone: http://eureka:${dev.eureka.password}@localhost:8761/eureka/

---

spring.profiles: prod
eureka.client.service-url.defaultZone: http://eureka:${prod.eureka.password}@localhost:8761/eureka/

