server:
  port: 8761

spring:
  security:
    user:
      name: eureka

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

---
spring.profiles: dev
spring.security.user.password: ${dev.eureka.password}
eureka.client.service-url.defaultZone: http://${spring.security.user.name}:${dev.eureka.password}@localhost:8761/eureka/
---
spring.profiles: prod
spring.security.user.password: ${prod.eureka.password}
---
spring.profiles: prod-peer1
spring.profiles.include:
  - prod
server.port: 8762
eureka:
  client.service-url.defaultZone: http://${spring.security.user.name}:${prod.eureka.password}@peer2:8763/eureka/
  instance: peer1
---
spring.profiles: prod-peer2
spring.profiles.include:
  - prod
server.port: 8763
eureka:
  client.service-url.defaultZone: http://${spring.security.user.name}:${prod.eureka.password}@peer1:8762/eureka/
  instance: peer2
